print ("Welcome to the MadLib! Insert your answer into the prompts below to begin")
animal1 = input ("Choose an animal: ")
animal2 = input ("Choose another animal: ")
color1 = input ("Choose a color: ")
color2 = input ("Choose another color: ")
color3 = input ("Choose one more color: ")
adjective1 = input ("Choose an adjective: ")
adjective2 = input ("Choose another adjective: ")

print (f"One {adjective1} {color1} {animal1} went down to the {color2} store and met up with a {adjective2} {color} {animal2}")
